---

- name: Debian | Install Firewalld
  apt: name=firewalld state=latest update_cache=yes
  
- name: Debian | Start and enable firewalld
  service: name=firewalld state=started enabled=yes

- name: "Debian | Fix: Link iptables file to /usr/sbin/"
  file:
    src: '/sbin/{{ item.src }}'
    dest: '/usr/sbin/{{ item.dest }}'
    state: link
  with_items:
    - { src: iptables, dest: iptables }
    - { src: iptables-restore, dest: iptables-restore }
    - { src: ip6tables, dest: ip6tables }
    - { src: ip6tables-restore, dest: ip6tables-restore }

- name: Debian | Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Debian | Add MongoDB 4.2 Apt Signing Key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.2.asc
    state: present

- name: Debian | add MongoDB Repository
  template:
    src: mongodb.list.j2
    dest: '/etc/apt/sources.list.d/mongodb.list'
    owner: root
    group: root
    mode: 0644

- name: Run the equivalent of "apt-get update"
  apt:
    update_cache: yes

- name: Debian | Installing mongodb
  apt:
    pkg: mongodb-org
    state: present
    update_cache: yes

- name: Debian | add firewall port 27017
  firewalld:
    port: 27017/tcp
    permanent: yes
    state: enabled
    immediate: true

- name: Debian | start mongodb service
  service:
    name: mongod
    state: stopped
    enabled: yes